LICENSE

The "LICENSE.md" has been added to the django website project for group "ordo_ab_chao". It's an MIT license.

adding MIT license to project

---

AUTHORS

has all four names of project members for C346 project.

AUTHORS document for ordo_ab_chao

---

doc/proposal.md

target audience, what we're selling, why it's important, why it's different from competition

proposal documentation of vision statement

---

doc/proposal.md

added '(our vision statement)'

---

doc/organization.md

These roles can change at any time. I just wanted to get this done. We will discuss this later this coming week. You all really need to choose your roles or I can get in trouble for being a 'project czar'.

organization document

---

README.md

I mixed up forking our project with making django from scratch, and have a bug report

update README and change mix-up

---

src/django_website/django_website/settings.py
src/django_website/django_website/tests/test_views.py

At I put one test for the django_website.views.py file. Enough for fulfill sprint one testing.

first test case in python from Sprint 1

---

README.md

corrected some spelling errors and was more specific about instructions

corrected some errors on README

---

doc/architecture.md

create blank architecture.md document

---

doc/proposal.md

make spot for 'estimations' on proposal.md doc

set up table on 'proposal.md'

---

doc/testing.md

create empty 'docs/testing.md' document with no table

create 'docs/testing.md' document

---

doc/STARUML_flowchart.mdj

This is to be added into the doc/architecture.md file.

STARUML data flowchart diagram image

---

doc/architecture.md

attempted to add STARUML diagram to architecture.md doc, I failed but I will leave this markdown in place for when I get the UML image correct.

attempted to add STARUML diagram

---

doc/architecture.md

The UML diagram image can now be displayed to the architecture.md file.

added STARUML data flowchart .png

---

doc/architecture.md

"use case diagram" added to architecture.md doc.

added use case diagram

---

doc/designpatterns.md

has place holder for future design patterns for the ordo_ab_chao django website.

create designpatterns markdown file

---

requirements.txt

This file isn't complete. I need to finish it when I get some time.

Create requirements.txt file for project

---

requirements.txt

finished all the requirements for the requirements.txt document. Shows dependencies.

finished requirements.txt

---

doc/testing.md

So I filled out the testing.md docuemnt for Sprint 4. I hope I made enough tests in the tests suite for our project for Prof. Sexton to give us an A.

filled out the doc/testing.md document

---

src/django_website/display_graphs/templates/display_graphs/graphs.html
src/django_website/display_graphs/views.py
src/django_website/django_website/tests/test_views.py
src/django_website/home_page/views.py

I made many tests in the testing suite to test our views, models and ebay api.

Addedtesting

---

src/django_website/display_graphs/templates/display_graphs/graphs.html
src/django_website/display_graphs/views.py
src/django_website/django_website/tests/test_views.py
src/django_website/home_page/views.py

I added more tests to the suite. Any of use can now look at the testing that's been done so far and use those tests to get an idea of how to do unit testing, as well as integration testing for this project.

Moretesting

---

src/django_website/about_us/static/about_us/style.css
src/django_website/about_us/templates/about_us/about.html

So I completed the look of the "about us" page. I hope you all like it.

finished the about us page

---

requirements.txt

added django-hitcount to dependencies.

added django-hitcount package

---

src/django_website/about_us/templates/about_us/about.html
src/django_website/blog/forms.py
src/django_website/blog/models.py
src/django_website/blog/templates/blog/form.html
src/django_website/blog/views.py

still working on the blog

---

README.md

added bug fix to README

---

doc/How_to_use_documentation/How_to_use.md

Updated doc

---

src/django_website/display_graphs/templates/display_graphs/graphs.html
src/django_website/display_graphs/views.py

GOT THE FIRST GRAPH WORKING! ONLY TOOK ME WEEKS TO GET THE THING WORKING! YAY!!!

got the first graph working

---

src/django_website/display_graphs/templates/display_graphs/graphs.html
src/django_website/display_graphs/views.py

Fixed problem with dates displaying in first graph. Set up second graph for first prediction model (commented out). I will start working on a prediction model now.

fixed date x-axis problem

---

src/django_website/display_graphs/views.py

Started working on the neural network.

started neural network

---

requirements.txt

Added dependencies to the requirements.txt doc.

added dependencies

---

src/django_website/display_graphs/neuralNetwork.py
src/django_website/display_graphs/outOfSample.py
src/django_website/display_graphs/templates/display_graphs/graphs.html
src/django_website/display_graphs/views.py

added the neural network. Unfortunately, it's broken right now. All the predictions are coming out as NaN's. I will have to fix this before adding the Multivariate Linear Regression model.

added neural network

---

src/django_website/display_graphs/mLinearRegression.py
src/django_website/display_graphs/templates/display_graphs/graphs.html
src/django_website/display_graphs/views.py
src/django_website/home_page/models.py

Added the Multivariate Linear Regression model to project. I got the neural network too not yield all 0's or 1.0's but is still far from okay. Needs a major overhaul with changes to activation functions, loss function, optimizer function, dropout rates (if any needed), number of neurons per  layer (power of 2 probably since using 'binary_crossentropy', and DEFINITELY CHANGE FEATURE SELECTION. The feature selection needs to be thoroughly examined for heavy correlation among features columns. There is probably massive correlation between some of the features used thus far.

added regression model

---

doc/How_to_use_documentation/images/blank.txt

images folder for 'how to use' folder

create images folder

---

src/django_website/about_us/static/about_us/style.css
src/django_website/about_us/urls.py
src/django_website/about_us/views.py
src/django_website/about_website/views.py
src/django_website/accounts/views.py
src/django_website/blog/admin.py
src/django_website/blog/forms.py
src/django_website/blog/models.py
src/django_website/blog/views.py
src/django_website/contact_us/views.py
src/django_website/directions/views.py
src/django_website/display_graphs/mLinearRegression.py
src/django_website/display_graphs/neuralNetwork.py
src/django_website/display_graphs/outOfSample.py
src/django_website/display_graphs/views.py
src/django_website/django_website/settings.py
src/django_website/django_website/urls.py
src/django_website/home_page/models.py
src/django_website/home_page/views.py

Hopefully, I don't need to make more changes and I can just focus on formatting and finishing the markdown docs and README.

made some final changes to the code

---

doc/How_to_use_documentation/How_to_use.md

added images and more complexity to the 'how to use' instructions

Updated how_to_use.md
